[package]
name = "rust_snake"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console = "0.15.0"
rand = "0.8.5"
spin_sleep = "1.1.1"
glfw = "0.44.0"
gl = "0.14.0"